---
- name: Update all packages except kernel
  yum:
    name: '*'
    update_cache: yes
    state: latest
    exclude: kernel*
- name: Install specified packages
  yum:
    name: "{{ yum_packages }}"
    state: latest
