---
- include_tasks: "{{ lookup('first_found', distributions) }}"
  vars:
    distributions:
      - "{{ ansible_facts['distribution'] }}.yml"
      - unsupported.yml

# This is required for rootless podman container to work under centos 7.
- name: Set max_user_namespaces
  sysctl:
    name: user.max_user_namespaces
    value: '28633'
    sysctl_file: /etc/sysctl.d/50-userns.conf
    reload: yes

# TODO: use pam_limits module to raise nofile limit.
# TODO: set basic vim config
