---
- name: OS is centos 7
  set_fact:
    distribution_to_setup: 'centos7'
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"

- name: Print error if OS is unsupported
  fail:
    msg: Unsupported OS
  when:
    - distribution_to_setup is undefined

